
// action types
const UPDATE_CURRENT = 'CHANGE_CURRENT';
const SET_CURRENT = 'SET_CURRENT';
const UPDATE_EXPRESSION = 'UPDATE_EXPRESSION';
const SET_EXPRESSION = 'SET_EXPRESSION';

export { UPDATE_CURRENT, SET_CURRENT, UPDATE_EXPRESSION, SET_EXPRESSION };