
// action types
const INCREMENT_BREAK = 'INCREMENT_BREAK';
const DECREMENT_BREAK = 'DECREMENT_BREAK';
const INCREMENT_SESSION = 'INCREMENT_SESSION';
const DECREMENT_SESSION = 'DECREMENT_SESSION';
const SET = 'SET';
const ISRUNNING = 'ISRUNNING';
export { DECREMENT_BREAK, ISRUNNING, DECREMENT_SESSION, INCREMENT_BREAK, INCREMENT_SESSION, SET };