
// action types
const INCREMENT_BREAK = 'INCREMENT_BREAK';
const DECREMENT_BREAK = 'DECREMENT_BREAK';
const INCREMENT_SESSION = 'INCREMENT_SESSION';
const DECREMENT_SESSION = 'DECREMENT_SESSION';
const SET = 'SET';

export { DECREMENT_BREAK, DECREMENT_SESSION, INCREMENT_BREAK, INCREMENT_SESSION, SET };